extends Node
class_name TestRunner

const COLOR_SUCCESS := "#22c55e"
const COLOR_ERROR := "#ef4444"
const COLOR_INFO := "#3b82f6"
const COLOR_DEBUG := "#9ca3af"

const INDEX_FILE := "res://tests/index.gd"
const TESTS_DIR := "res://tests"
const TESTS_AUTOWRAPPER_DIR := "res://tests/autowrapper"

var log_label: RichTextLabel
var indent_level: int = 0
var total_passed: int = 0
var total_failed: int = 0
var is_headless := false
var tests_complete := false
var bootstrap_error := false
var test_filter: String = ""

var _worker_thread: Thread

static var ctx := TestContext.new()


class TestContext:
	var runner: TestRunner = null
	var current_test: String = ""

	func log_info(msg: String) -> void:
		if runner:
			runner._log("[%s] %s" % [current_test, msg], COLOR_INFO)

	func log_debug(msg: String) -> void:
		if runner:
			runner._log("[%s] %s" % [current_test, msg], COLOR_DEBUG)

	func log_error(msg: String) -> void:
		if runner:
			runner._log("[%s] %s" % [current_test, msg], COLOR_ERROR)


func _ready() -> void:
	is_headless = DisplayServer.get_name() == "headless"

	if not is_headless:
		log_label = $ScrollContainer/LogLabel
		log_label.text = ""

	ctx.runner = self

	test_filter = OS.get_environment("GODOT_TEST_RUNNER_FILTER")

	# Set up a timeout failsafe in case tests get stuck.
	var timeout_ms := 600000
	var timeout_str := OS.get_environment("GODOT_TEST_RUNNER_TIMEOUT")
	if timeout_str != "":
		timeout_ms = int(timeout_str)

	get_tree().create_timer(timeout_ms / 1000.0).timeout.connect(_on_timeout)

	log_info("Starting test session")
	indent_level += 1

	_try_regenerate_test_index()

	var test_files := _get_test_files()
	if bootstrap_error:
		indent_level -= 1
		tests_complete = true
		_quit_tests_now(1)
		return

	if test_files.is_empty():
		log_info("No test suites found (empty wrapper)")
		indent_level -= 1
		tests_complete = true
		_quit_tests_now(0)
		return

	if is_headless:
		_run_all_suites(test_files)
		_finish()
	else:
		# Run suites on a background thread so the UI stays responsive.
		_worker_thread = Thread.new()
		_worker_thread.start(_run_all_suites_threaded.bind(test_files))


func _run_all_suites_threaded(test_files: Array[String]) -> void:
	_run_all_suites(test_files)
	call_deferred("_on_suites_complete")


func _on_suites_complete() -> void:
	if _worker_thread:
		_worker_thread.wait_to_finish()
		_worker_thread = null
	_finish()


func _finish() -> void:
	indent_level -= 1
	log_info("==============================")

	if total_failed > 0:
		log_error("FAILED: %d passed, %d failed" % [total_passed, total_failed])
	else:
		log_success("PASSED: %d tests total" % total_passed)

	tests_complete = true
	_quit_tests_now(1 if total_failed > 0 else 0)


func _run_all_suites(test_files: Array[String]) -> void:
	for file in test_files:
		_run_suite(file)


func _try_regenerate_test_index() -> void:
	# Regenerate the test index from the filesystem so newly added test
	# files are picked up automatically. The checked-in index.gd serves
	# exported builds where DirAccess/FileAccess can't enumerate or write.

	var test_files := _discover_test_files()
	if test_files.is_empty():
		# Cannot enumerate files (exported build) or no tests.
		# The bundled index.gd handles this case.
		return

	_write_test_index(test_files)


func _discover_test_files() -> Array[String]:
	var seen: Dictionary = {}
	var test_files: Array[String] = []

	_collect_test_files(TESTS_DIR, "res://tests/", test_files, seen)
	_collect_test_files(TESTS_AUTOWRAPPER_DIR, "res://tests/autowrapper/", test_files, seen)

	test_files.sort()
	return test_files


func _collect_test_files(dir_path: String, resource_prefix: String, out_files: Array[String], seen: Dictionary) -> void:
	var dir := DirAccess.open(dir_path)
	if dir == null:
		return

	dir.list_dir_begin()
	while true:
		var fname := dir.get_next()
		if fname == "":
			break

		if dir.current_is_dir():
			continue

		if fname.begins_with("test_") and fname.ends_with(".gd"):
			var path := resource_prefix + fname
			if not seen.has(path):
				seen[path] = true
				out_files.append(path)
	dir.list_dir_end()


func _write_test_index(test_files: Array[String]) -> void:
	var header := """# WARNING: This file is auto-generated by TestRunner._write_test_index()
# Do not edit manually. Changes will be overwritten on each test run.
# This file is necessary for test runner compatibility with exported binaries.

"""
	var content := header

	if test_files.is_empty():
		content += "const SUITES := []\n"
	else:
		content += "const SUITES := [\n"
		for fname in test_files:
			content += "\t\"%s\",\n" % fname
		content += "]\n"

	var file := FileAccess.open(INDEX_FILE, FileAccess.WRITE)
	if file == null:
		log_debug("Note: Could not regenerate test index (expected in exported builds)")
		return

	file.store_string(content)


func _get_test_files() -> Array[String]:
	var suites := _load_index_suites()
	if bootstrap_error:
		return []

	if not suites.is_empty():
		return suites

	# Fallback: Try to discover test files dynamically (only works in editor).
	return _discover_test_files()


func _load_index_suites() -> Array[String]:
	var suites: Array[String] = []

	# If the index file isn't present as a script resource, fall back to scanning.
	if not ResourceLoader.exists(INDEX_FILE, "Script"):
		return suites

	var index := ResourceLoader.load(INDEX_FILE, "Script") as Script
	if index == null:
		bootstrap_error = true
		log_error("Failed to load test index: %s" % INDEX_FILE)
		return suites

	# Only reload when source exists. Valid exported/tokenized scripts may not
	# have source code even though they are fine to use.
	if index.has_source_code():
		var reload_error: int = index.reload()
		if reload_error != OK:
			bootstrap_error = true
			log_error("Script error in %s (reload error %d)" % [INDEX_FILE, reload_error])
			return suites

	var constants := index.get_script_constant_map()
	if constants.has("SUITES"):
		var raw_suites = constants["SUITES"]
		if raw_suites is Array:
			for suite_path in raw_suites:
				if suite_path is String:
					suites.append(suite_path)

	return suites


func _on_timeout() -> void:
	if not tests_complete:
		log_error("Test runner timeout after GODOT_TEST_RUNNER_TIMEOUT seconds")
		if is_instance_valid(get_tree()):
			get_tree().quit(1)


func _run_suite(path: String) -> void:
	var file := path.get_file()
	var suite_name := file.trim_suffix(".gd")

	if not _matches_filter_prefix(suite_name):
		return

	var script := load(path)

	if script == null:
		log_error("Failed to load: %s" % path)
		total_failed += 1
		return

	if script is Script and script.has_source_code():
		var reload_error: int = script.reload()
		if reload_error != OK:
			log_error("Script error in %s (reload error %d)" % [path, reload_error])
			total_failed += 1
			return

	var methods: Array[String] = []
	for m in script.get_script_method_list():
		if m.has("name") and String(m["name"]).begins_with("test_"):
			methods.append(String(m["name"]))

	methods.sort()

	if methods.is_empty():
		return

	var filtered_methods: Array[String] = []
	for method in methods:
		if _matches_filter(suite_name, method):
			filtered_methods.append(method)

	if filtered_methods.is_empty():
		return

	# Optional per-suite lifecycle hooks: _suite_setup() runs before the first
	# test, _suite_teardown() after the last. Used e.g. by test_exception_repro
	# to temporarily disable push_error spam from expected exceptions.
	var setup_instance: Object = null
	if script.can_instantiate():
		setup_instance = script.new()
		if setup_instance != null and setup_instance.has_method("_suite_setup"):
			setup_instance.call("_suite_setup")

	log_info("Suite: %s" % suite_name)
	indent_level += 1

	var suite_passed := 0
	var suite_failed := 0
	var suite_start := Time.get_ticks_usec()

	for method in filtered_methods:
		ctx.current_test = "%s.%s" % [suite_name, method]

		var start := Time.get_ticks_usec()
		var result := _run_test(script, method)
		var duration_ms := (Time.get_ticks_usec() - start) / 1000.0

		if result == "":
			log_success("✓ %s (%.3f ms)" % [method, duration_ms])
			suite_passed += 1
		else:
			log_error("✗ %s: %s (%.3f ms)" % [method, result, duration_ms])
			suite_failed += 1

			var stack = get_stack()
			for frame in stack:
				if frame is Dictionary and String(frame.get("source", "")).begins_with("res://tests"):
					log_debug("  at %s:%d" % [frame.get("source", "?"), frame.get("line", 0)])

		ctx.current_test = ""

	if setup_instance != null and setup_instance.has_method("_suite_teardown"):
		setup_instance.call("_suite_teardown")
	if setup_instance != null and not setup_instance is RefCounted:
		setup_instance.free()

	var suite_duration_ms := (Time.get_ticks_usec() - suite_start) / 1000.0

	indent_level -= 1
	log_info("Suite result: %s [%d/%d] (%.3f ms)" %
		[suite_name, suite_passed, suite_passed + suite_failed, suite_duration_ms])

	total_passed += suite_passed
	total_failed += suite_failed


func _filter_patterns() -> Array[String]:
	var patterns: Array[String] = []
	for raw in test_filter.split(","):
		var p := raw.strip_edges()
		if not p.is_empty():
			patterns.append(p)
	return patterns


func _matches_filter_prefix(suite_name: String) -> bool:
	if test_filter.is_empty():
		return true
	for pattern in _filter_patterns():
		var dot_idx := pattern.find(".")
		if dot_idx < 0:
			if suite_name.matchn(pattern):
				return true
		elif suite_name.matchn(pattern.substr(0, dot_idx)):
			return true
	return false


func _matches_filter(suite_name: String, method_name: String) -> bool:
	if test_filter.is_empty():
		return true
	var qualified := "%s.%s" % [suite_name, method_name]
	for pattern in _filter_patterns():
		if qualified.matchn(pattern):
			return true
		# A bare suite name (no wildcard, no method suffix) selects the whole
		# suite; a wildcard without a method suffix selects by suite name too.
		if pattern.find(".") < 0 and suite_name.matchn(pattern):
			return true
	return false


func _run_test(script: Object, method: String) -> String:
	var instance = script.new()
	if instance == null:
		return "Failed to instantiate script"

	if not instance.has_method(method):
		_free_test_instance(instance)
		return "Instance method not found: %s" % method

	var result = instance.call(method)
	_free_test_instance(instance)

	match typeof(result):
		TYPE_STRING:
			if result == "OK":
				return ""
			elif result == "":
				return "Test returned empty string. Return \"OK\" for success."
			else:
				return result

		TYPE_NIL:
			return ""

		_:
			return "Invalid return type: expected \"OK\" or error String"


func _free_test_instance(instance: Object) -> void:
	# Tests extend Node. free() clears the script's instance list so a later
	# reload() doesn't fail with ERR_ALREADY_IN_USE (leaked instances would
	# block re-running the suites). RefCounted tests release themselves.
	if not instance is RefCounted:
		instance.free()


func log_success(message: String) -> void:
	_log(message, COLOR_SUCCESS)


func log_error(message: String) -> void:
	_log(message, COLOR_ERROR)


func log_info(message: String) -> void:
	_log(message, COLOR_INFO)


func log_debug(message: String) -> void:
	_log(message, COLOR_DEBUG)


func _log(message: String, color: String) -> void:
	var indent := "  ".repeat(indent_level)
	var formatted := "[color=%s]%s%s[/color]" % [color, indent, message]

	# print_rich is thread-safe.
	print_rich(formatted)

	# UI updates must happen on the main thread.
	if not is_headless and log_label:
		call_deferred("_apply_log", formatted)


func _apply_log(formatted: String) -> void:
	if not log_label:
		return
	log_label.text += ("\n" if log_label.text != "" else "") + formatted
	var sc := log_label.get_parent()
	if sc is ScrollContainer:
		sc.scroll_vertical = int(sc.get_v_scroll_bar().max_value)


# Only auto-quits when running in headless or GODOT_TEST_RUNNER mode.
# In game mode (desktop/mobile), stays open so the user can see results
# regardless of pass/fail.
func _quit_tests_now(code: int) -> void:
	var env_test_runner := OS.get_environment("GODOT_TEST_RUNNER") == "true"
	var is_headless_mode := DisplayServer.get_name() == "headless"
	var should_quit := env_test_runner or is_headless_mode

	if should_quit:
		get_tree().quit(code)
